[package]
name = "scah-python"
version = "0.0.1"
edition = "2024"

[lib]
name = "scah"
crate-type = ["cdylib"]

[dependencies]
scah = { path = ".." }
pyo3 = { version = "0.27.2", features = ["extension-module"] }
